language: bash

sudo: required

os: linux
dist: trusty

services:
  - docker

install:
  - echo "install nothing!"

script:
  - echo "no tests!"
  - docker --version
  - docker build -t latest .
  - docker images
  - docker tag latest zltoxicnetherlz/game-server
  - docker push zltoxicnetherlz/game-server