spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

application:
  game:
    transport: websocket

logging:
  level:
    root: INFO
    org.springframework: INFO
